#!/bin/bash
# Script to apply debug patches to SGLang

echo "This script will help you apply debug patches to SGLang"
echo "You need to manually edit the files based on the patch files created"
echo ""
echo "Files to modify:"
echo "1. python/sglang/srt/managers/scheduler.py"
echo "2. python/sglang/srt/managers/scheduler_output_processor_mixin.py"
echo "3. python/sglang/srt/managers/tokenizer_manager.py"
echo ""
echo "Instructions:"
echo "1. Open each file in your editor"
echo "2. Find the locations mentioned in the patch files"
echo "3. Add the debug logging code"
echo "4. Save and restart the SGLang servers"
echo ""
echo "After applying patches, run the servers with:"
echo "python -m sglang.launch_server ... --log-level info"
echo ""
echo "Then check the server logs for [DEBUG] messages"
